# ASML Stocks Trend Prediction

## Team Toilet


Describe the objective

In [28]:
import pandas as pd
import numpy as np
from ta import volume, trend, momentum, volatility
from ta.utils import dropna

### Feature Creation

We selected some feature present in our references [1], [2]:

| Indicator | library |
| ----------- | ----------- |
| On balance volume (OBV) | ta |
| Price-earning ratio (PER) | - | 
| Return on investment (ROI) | - |
| 6 days moving average (MA6) | ta |
| 10 days moving average (MA10) | ta |
| 6 days relative strength index (RSI6) | ta|
| 10 days relative strength index (RSI10) |ta |
| 9 days K line (K9) | - |
| 9 days D line (D9) | - |
| Moving average convergence & divergence (MACD) | ta |
| Difference (DIF) | ta  EMA(12) - EMA()|
| 6 days autoregressive (AR6) | - |
| 10 days autoregressive (AR10) | - |
| 10 days BR index (BR10) | - |
| 20 days BR index (BR20) | - |
| 10 days volatility ratio (VR10) | Replaced by Average True Range for window of 10 days |
| 20 days volatility ratio (VR20) | Replaced by Average True Range for window of 10 days |
| 6 days bias (BIAS6) | (Close - MA6)/6 |
| 10 days bias (BIAS10) | (Close - MA10)/10 |
| 6 days williams% rate (WMS6) | ta (Willians % R ?)|
| 10 days williams% rate (WMS10) | ta (Willians % R ?)|
| Total amount per weighted stock price index (TAPI) | Volume/Close |
| 6 days psychological line (PSY6) | ? |
| 10 days psychological line (PSY10) | ? |


[1]: Y. Lin, H. Guo and J. Hu, "An SVM-based approach for stock market trend prediction," The 2013 International Joint Conference on Neural Networks (IJCNN), 2013, pp. 1-7, doi: 10.1109/IJCNN.2013.6706743.

[2]: Chenn-Jung Huang, Dian-Xiu Yang, Yi-Ta Chuang, "Application of wrapper approach and composite classifier to the stock trend prediction", Expert Systems with Applications, Volume 34, Issue 4, 2008, Pages 2870-2878, ISSN 0957-4174, DOI: https://doi.org/10.1016/j.eswa.2007.05.035.

In [29]:
# Load dataset
df = pd.read_csv('data/ASML.csv', sep=',')
df = dropna(df)

In [30]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2016-11-17,101.239998,102.849998,101.190002,102.559998,97.645622,1344700
1,2016-11-18,103.580002,104.750000,103.379997,104.589996,99.578346,1914300
2,2016-11-21,104.089996,105.110001,104.019997,105.089996,100.054390,1408200
3,2016-11-22,105.449997,105.610001,104.800003,105.320000,100.273384,876300
4,2016-11-23,104.480003,105.349998,104.250000,105.099998,100.063911,432300

In [31]:
df.shape

(1258, 7)

In [32]:
obv = volume.OnBalanceVolumeIndicator(close=df["Close"], volume=df["Volume"])
ma6 = trend.SMAIndicator(close=df["Close"], window=6)
ma10 = trend.SMAIndicator(close=df["Close"], window=10)
rsi6 = momentum.RSIIndicator(close=df["Close"], window=6)
rsi10 = momentum.RSIIndicator(close=df["Close"], window=10)
macd = trend.MACD(close=df["Close"]) # dunno if it is right
atr10 = volatility.AverageTrueRange(high=df["High"], low=df["Low"], close=df["Close"], window=10)
atr20 = volatility.AverageTrueRange(high=df["High"], low=df["Low"], close=df["Close"], window=20)
wms6 = momentum.WilliamsRIndicator(high=df["High"], low=df["Low"], close=df["Close"], lbp=6)
wms10 = momentum.WilliamsRIndicator(high=df["High"], low=df["Low"], close=df["Close"], lbp=10)

In [33]:
df['obv'] = obv.on_balance_volume()
df['ma6'] = ma6.sma_indicator()
df['ma10'] = ma10.sma_indicator()
df['rsi6'] = rsi6.rsi()
df['rsi10'] = rsi10.rsi()
df['macd'] = macd.macd()
df['dif'] = macd.macd_diff()
df['atr10'] = atr10.average_true_range()
df['atr20'] = atr20.average_true_range()
df['bias6'] = (df['Close'] - df['ma6'])/6
df['bias10'] = (df['Close'] - df['ma10'])/10
df['tapi'] = df['Volume']/df['Close']
df['wms6'] = wms6.williams_r()
df['wms10'] = wms10.williams_r()

In [34]:
df.head(35)

,Date,Open,High,Low,Close,Adj Close,Volume,obv,ma6,ma10,...,rsi10,macd,dif,atr10,atr20,bias6,bias10,tapi,wms6,wms10
0,2016-11-17,101.239998,102.849998,101.190002,102.559998,97.645622,1344700,1344700,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,13111.349710,NaN,NaN
1,2016-11-18,103.580002,104.750000,103.379997,104.589996,99.578346,1914300,3259000,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,18302.897726,NaN,NaN
2,2016-11-21,104.089996,105.110001,104.019997,105.089996,100.054390,1408200,4667200,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,13399.943416,NaN,NaN
3,2016-11-22,105.449997,105.610001,104.800003,105.320000,100.273384,876300,5543500,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,8320.357007,NaN,NaN
4,2016-11-23,104.480003,105.349998,104.250000,105.099998,100.063911,432300,5111200,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,4113.225578,NaN,NaN
5,2016-11-25,103.989998,104.459999,103.769997,104.139999,99.149918,251900,4859300,104.466664,NaN,...,NaN,NaN,NaN,0.000000,0.000000,-0.054444,NaN,2418.859251,-33.257971,NaN
6,2016-11-28,103.300003,103.910004,103.220001,103.629997,98.664352,453200,4406100,104.644998,NaN,...,NaN,NaN,NaN,0.000000,0.000000,-0.169167,NaN,4373.251116,-82.845356,NaN
7,2016-11-29,102.879997,104.010002,102.709999,103.790001,98.816681,1194200,5600300,104.511665,NaN,...,NaN,NaN,NaN,0.000000,0.000000,-0.120277,NaN,11505.925315,-62.758577,NaN
8,2016-11-30,103.769997,103.820000,102.930000,103.129997,98.188309,434200,5166100,104.184999,NaN,...,NaN,NaN,NaN,0.000000,0.000000,-0.175834,NaN,4210.220233,-85.517320,NaN
9,2016-12-01,102.669998,102.739998,99.680000,99.989998,95.198776,837900,4328200,103.296665,103.733998,...,21.906053,NaN,NaN,1.474000,0.000000,-0.551111,-0.3744,8379.838151,-94.532661,-94.772379
10,2016-12-02,99.010002,100.300003,98.839996,99.779999,94.998840,701100,3627100,102.409998,103.455998,...,21.115273,NaN,NaN,1.472600,0.000000,-0.438333,-0.3676,7026.458278,-83.273977,-86.115180
11,2016-12-05,102.290001,103.019997,101.690002,102.919998,97.988373,818600,4445700,102.206665,103.288998,...,50.688977,NaN,NaN,1.649340,0.000000,0.118889,-0.0369,7953.750640,-21.083225,-39.734136
12,2016-12-06,101.889999,102.900002,101.790001,102.709999,97.788429,399900,4045800,102.053332,103.050999,...,49.315131,NaN,NaN,1.597406,0.000000,0.109444,-0.0341,3893.486553,-25.145097,-42.836039
13,2016-12-07,101.980003,103.919998,101.830002,103.550003,98.588196,566600,4612400,102.013332,102.873999,...,54.764270,NaN,NaN,1.646665,0.000000,0.256112,0.0676,5471.752618,-7.283363,-27.649684
14,2016-12-08,103.190002,103.730003,102.650002,103.110001,98.169273,478800,4133600,102.010000,102.674999,...,51.539348,NaN,NaN,1.589998,0.000000,0.183334,0.0435,4643.584476,-15.944817,-24.021304
15,2016-12-09,102.919998,103.110001,102.089996,102.660004,97.740837,362500,3771100,102.455001,102.527000,...,48.306816,NaN,NaN,1.532999,0.000000,0.034167,0.0133,3531.073309,-24.803022,-26.112117
16,2016-12-12,103.169998,103.339996,102.410004,102.900002,97.969337,308500,4079600,102.975001,102.454000,...,50.159255,NaN,NaN,1.472698,0.000000,-0.012500,0.0446,2998.056307,-45.739813,-21.469994
17,2016-12-13,104.110001,104.860001,104.000000,104.639999,99.625946,308400,4388000,103.261668,102.539000,...,61.324035,NaN,NaN,1.521428,0.000000,0.229722,0.2101,2947.247735,-7.166189,-3.654515
18,2016-12-14,104.580002,104.940002,103.529999,103.629997,98.664352,390800,3997200,103.415001,102.589000,...,53.582613,NaN,NaN,1.510286,0.000000,0.035833,0.1041,3771.108861,-42.122347,-21.475471
19,2016-12-15,104.470001,105.389999,104.320000,105.029999,99.997276,655400,4652600,103.661667,103.093000,...,61.138326,NaN,NaN,1.535258,1.541000,0.228055,0.1937,6240.121929,-10.909081,-5.496181
20,2016-12-16,106.260002,106.720001,105.959999,106.239998,101.149292,865800,5518400,104.183333,103.739000,...,66.391876,NaN,NaN,1.550732,1.548450,0.342777,0.2501,8149.473045,-10.367224,-9.542805
21,2016-12-19,108.360001,110.480003,108.360001,110.220001,104.938576,1709400,7227800,105.443333,104.469000,...,77.505635,NaN,NaN,1.819659,1.683028,0.796111,0.5751,15508.981895,-3.221834,-2.991967
22,2016-12-20,109.370003,109.800003,109.110001,109.709999,104.453018,810500,6417300,106.578332,105.169000,...,74.020538,NaN,NaN,1.748693,1.654376,0.521944,0.4541,7387.658439,-11.079188,-8.901779
23,2016-12-21,110.029999,110.300003,109.720001,110.050003,104.776718,659500,7076800,107.480000,105.819000,...,74.857974,NaN,NaN,1.632824,1.601158,0.428334,0.4231,5992.730414,-6.187047,-5.125145
24,2016-12-22,110.360001,110.419998,109.769997,109.980003,104.710083,324200,6752600,108.538334,106.506000,...,74.310025,NaN,NaN,1.534542,1.553600,0.240278,0.3474,2947.808612,-8.116879,-5.959471
25,2016-12-23,110.419998,110.849998,110.269997,110.730003,105.424133,183900,6936500,109.488335,107.313000,...,76.369235,1.878188,NaN,1.468087,1.519420,0.206945,0.3417,1660.796487,-2.453886,-1.421743
26,2016-12-27,110.790001,111.620003,110.790001,111.510002,106.166779,308500,7245000,110.366669,108.174000,...,78.372480,2.062190,NaN,1.410279,1.487949,0.190556,0.3336,2766.567971,-3.374262,-1.359715
27,2016-12-28,110.809998,111.309998,110.430000,110.779999,105.471748,509900,6735100,110.460001,108.788000,...,72.023304,2.124617,NaN,1.377251,1.467551,0.053333,0.1992,4602.816434,-33.466268,-10.383233
28,2016-12-29,110.970001,111.370003,110.699997,111.160004,105.833542,754900,7490000,110.701669,109.541001,...,73.275536,2.179629,NaN,1.306526,1.427674,0.076389,0.1619,6791.111666,-24.210448,-6.301354
29,2016-12-30,112.059998,112.660004,111.269997,112.199997,106.823700,858700,8348700,111.060001,110.258001,...,76.477203,2.280852,NaN,1.325874,1.431290,0.189999,0.1942,7653.297887,-15.917159,-6.865771
30,2017-01-03,110.980003,111.279999,110.150002,110.449997,105.157555,874700,7474000,111.138334,110.679001,...,62.481791,2.194565,NaN,1.398286,1.462226,-0.114723,-0.0229,7919.420767,-88.048017,-51.395476
31,2017-01-04,109.839996,110.349998,109.620003,109.919998,104.652954,846200,6627800,111.003333,110.649001,...,58.857288,2.059672,NaN,1.341457,1.430614,-0.180556,-0.0729,7698.326195,-90.131747,-77.183202
32,2017-01-05,110.800003,111.900002,110.750000,111.239998,105.909706,493800,7121600,110.958332,110.802000,...,64.548288,2.035814,NaN,1.405311,1.458084,0.046944,0.0438,4439.050781,-46.710708,-46.710708
33,2017-01-06,110.559998,111.589996,110.300003,111.120003,105.795464,360200,6761400,111.015000,110.909000,...,63.658879,1.984350,-0.069297,1.393780,1.449679,0.017501,0.0211,3241.540589,-50.657911,-50.657911
34,2017-01-09,111.019997,112.730003,111.010002,112.489998,107.099808,554800,7316200,111.236665,111.160000,...,69.065999,2.030702,-0.018355,1.426402,1.463195,0.208889,0.1330,4931.994043,-7.717203,-7.717203

In [35]:
df.to_csv("data/ASML_v1.csv")

In [36]:
df['daily_diff'] = df['Close'].shift(-1) - df['Close']

In [37]:
df['daily_trend'] = np.sign(df['daily_diff'])

In [38]:
df['daily_trend']

0       1.0
1       1.0
2       1.0
3      -1.0
4      -1.0
       ...
1253    1.0
1254    1.0
1255    1.0
1256    1.0
1257    NaN
Name: daily_trend, Length: 1258, dtype: float64

In [39]:
df.to_csv("data/ASML_v1_with_trend.csv")