# ASML Stocks Trend Prediction

## Team Toilet


Describe the objective

In [1]:
import pandas as pd
import numpy as np
from ta import volume, trend, momentum, volatility
from ta.utils import dropna

### Feature Creation

We selected some feature present in our references [1], [2]:

| Indicator | library |
| ----------- | ----------- |
| On balance volume (OBV) | ta |
| Price-earning ratio (PER) | - | 
| Return on investment (ROI) | - |
| 6 days moving average (MA6) | ta |
| 10 days moving average (MA10) | ta |
| 6 days relative strength index (RSI6) | ta|
| 10 days relative strength index (RSI10) |ta |
| 9 days K line (K9) | - |
| 9 days D line (D9) | - |
| Moving average convergence & divergence (MACD) | ta |
| Difference (DIF) | ta  EMA(12) - EMA()|
| 6 days autoregressive (AR6) | - |
| 10 days autoregressive (AR10) | - |
| 10 days BR index (BR10) | - |
| 20 days BR index (BR20) | - |
| 10 days volatility ratio (VR10) | Replaced by Average True Range for window of 10 days |
| 20 days volatility ratio (VR20) | Replaced by Average True Range for window of 10 days |
| 6 days bias (BIAS6) | (Close - MA6)/6 |
| 10 days bias (BIAS10) | (Close - MA10)/10 |
| 6 days williams% rate (WMS6) | ta (Willians % R ?)|
| 10 days williams% rate (WMS10) | ta (Willians % R ?)|
| Total amount per weighted stock price index (TAPI) | Volume/Close |
| 6 days psychological line (PSY6) | ? |
| 10 days psychological line (PSY10) | ? |


[1]: Y. Lin, H. Guo and J. Hu, "An SVM-based approach for stock market trend prediction," The 2013 International Joint Conference on Neural Networks (IJCNN), 2013, pp. 1-7, doi: 10.1109/IJCNN.2013.6706743.

[2]: Chenn-Jung Huang, Dian-Xiu Yang, Yi-Ta Chuang, "Application of wrapper approach and composite classifier to the stock trend prediction", Expert Systems with Applications, Volume 34, Issue 4, 2008, Pages 2870-2878, ISSN 0957-4174, DOI: https://doi.org/10.1016/j.eswa.2007.05.035.

In [2]:
# Load dataset
df = pd.read_csv('data/ASML.csv', sep=',')
df = dropna(df)

In [3]:
df.head()

         Date       Open       High        Low      Close  Adj Close   Volume
0  2010-12-02  34.130001  35.020000  34.099998  34.880001  24.917583  1921900
1  2010-12-03  35.049999  35.669998  35.009998  35.580002  25.417646  1591600
2  2010-12-06  35.340000  35.480000  34.880001  35.180000  25.131891  2002000
3  2010-12-07  35.279999  35.349998  34.709999  34.750000  24.824713  1417000
4  2010-12-08  34.560001  35.240002  34.560001  35.169998  25.124748  2339100

In [4]:
df.shape

(2769, 7)

In [5]:
obv = volume.OnBalanceVolumeIndicator(close=df["Close"], volume=df["Volume"])
ma6 = trend.SMAIndicator(close=df["Close"], window=6)
ma10 = trend.SMAIndicator(close=df["Close"], window=10)
rsi6 = momentum.RSIIndicator(close=df["Close"], window=6)
rsi10 = momentum.RSIIndicator(close=df["Close"], window=10)
macd = trend.MACD(close=df["Close"]) # dunno if it is right
atr10 = volatility.AverageTrueRange(high=df["High"], low=df["Low"], close=df["Close"], window=10)
atr20 = volatility.AverageTrueRange(high=df["High"], low=df["Low"], close=df["Close"], window=20)
wms6 = momentum.WilliamsRIndicator(high=df["High"], low=df["Low"], close=df["Close"], lbp=6)
wms10 = momentum.WilliamsRIndicator(high=df["High"], low=df["Low"], close=df["Close"], lbp=10)

In [6]:
df['obv'] = obv.on_balance_volume()
df['ma6'] = ma6.sma_indicator()
df['ma10'] = ma10.sma_indicator()
df['rsi6'] = rsi6.rsi()
df['rsi10'] = rsi10.rsi()
df['macd'] = macd.macd()
df['dif'] = macd.macd_diff()
df['atr10'] = atr10.average_true_range()
df['atr20'] = atr20.average_true_range()
df['bias6'] = (df['Close'] - df['ma6'])/6
df['bias10'] = (df['Close'] - df['ma10'])/10
df['tapi'] = df['Volume']/df['Close']

In [7]:
df.head(35)

,Date,Open,High,Low,Close,Adj Close,Volume,obv,ma6,ma10,rsi6,rsi10,macd,dif,atr10,atr20,bias6,bias10,tapi
0,2010-12-02,34.130001,35.020000,34.099998,34.880001,24.917583,1921900,1921900,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,55100.342457
1,2010-12-03,35.049999,35.669998,35.009998,35.580002,25.417646,1591600,3513500,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,44732.993551
2,2010-12-06,35.340000,35.480000,34.880001,35.180000,25.131891,2002000,1511500,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,56907.333712
3,2010-12-07,35.279999,35.349998,34.709999,34.750000,24.824713,1417000,94500,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,40776.978417
4,2010-12-08,34.560001,35.240002,34.560001,35.169998,25.124748,2339100,2433600,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,66508.391613
5,2010-12-09,37.070000,37.990002,37.070000,37.740002,26.960703,9843600,12277200,35.550001,NaN,86.004767,NaN,NaN,NaN,0.000000,0.000000,0.365000,NaN,260826.695240
6,2010-12-10,37.810001,37.840000,37.349998,37.400002,26.717817,3428000,8849200,35.970001,NaN,77.641404,NaN,NaN,NaN,0.000000,0.000000,0.238334,NaN,91657.749109
7,2010-12-13,37.369999,37.590000,37.119999,37.330002,26.667812,2633700,6215500,36.261667,NaN,75.819851,NaN,NaN,NaN,0.000000,0.000000,0.178056,NaN,70551.831205
8,2010-12-14,37.160000,37.349998,36.889999,37.130001,26.524931,2358100,3857400,36.586667,NaN,70.175076,NaN,NaN,NaN,0.000000,0.000000,0.090556,NaN,63509.289967
9,2010-12-15,36.919998,37.220001,36.500000,36.700001,26.217751,1450700,2406700,36.911668,36.186001,58.867777,62.620920,NaN,NaN,0.869001,0.000000,-0.035278,0.0514,39528.609277
10,2010-12-16,37.040001,37.189999,36.790001,37.160000,26.546362,1337100,3743800,37.243335,36.414001,65.917568,67.302302,NaN,NaN,0.831100,0.000000,-0.013889,0.0746,35982.238967
11,2010-12-17,37.580002,38.259998,37.459999,38.220001,27.303608,2508900,6252700,37.323334,36.678001,76.876672,75.241500,NaN,NaN,0.857990,0.000000,0.149444,0.1542,65643.640355
12,2010-12-20,38.119999,38.279999,37.759998,37.869999,27.053572,1670300,4582400,37.401667,36.947001,68.188984,69.087198,NaN,NaN,0.824191,0.000000,0.078055,0.0923,44106.153792
13,2010-12-21,38.160000,38.180000,37.750000,37.980000,27.132156,1347300,5929700,37.510000,37.270001,69.489358,69.945643,NaN,NaN,0.784772,0.000000,0.078333,0.0710,35473.933649
14,2010-12-22,38.270000,38.320000,37.980000,38.310001,27.367908,890500,6820200,37.706667,37.584001,73.403332,72.491946,NaN,NaN,0.740295,0.000000,0.100556,0.0726,23244.583053
15,2010-12-23,37.869999,38.080002,37.740002,37.860001,27.046436,588800,6231400,37.900000,37.596001,60.668135,64.244941,NaN,NaN,0.723265,0.000000,-0.006667,0.0264,15552.033398
16,2010-12-27,38.169998,38.490002,37.900002,38.450001,27.467913,654200,6885600,38.115001,37.701001,69.102219,69.328205,NaN,NaN,0.713939,0.000000,0.055833,0.0749,17014.303849
17,2010-12-28,38.480000,38.869999,38.180000,38.299999,27.360760,889800,5995800,38.128333,37.798000,64.859051,66.651399,NaN,NaN,0.711545,0.000000,0.028611,0.0502,23232.376586
18,2010-12-29,38.000000,38.250000,37.830002,38.049999,27.182163,725100,5270700,38.158333,37.890000,57.765102,62.203811,NaN,NaN,0.687390,0.000000,-0.018056,0.0160,19056.505100
19,2010-12-30,38.619999,38.779999,38.360001,38.430000,27.453627,1163700,6434400,38.233333,38.063000,64.789588,66.031953,NaN,NaN,0.691651,0.733000,0.032778,0.0367,30281.030445
20,2010-12-31,38.380001,38.549999,38.189999,38.340000,27.389336,623800,5810600,38.238333,38.181000,61.865241,64.317658,NaN,NaN,0.658486,0.714350,0.016944,0.0159,16270.213876
21,2011-01-03,38.810001,39.230000,38.610001,38.660000,27.617931,2587600,8398200,38.371666,38.225000,68.023325,67.636952,NaN,NaN,0.681637,0.723132,0.048056,0.0435,66932.229695
22,2011-01-04,38.369999,38.459999,37.180000,37.389999,26.710672,2975700,5422500,38.195000,38.177000,38.451689,47.962401,NaN,NaN,0.761474,0.760976,-0.134167,-0.0787,79585.452784
23,2011-01-05,36.340000,36.939999,36.209999,36.630001,26.167746,4655200,767300,37.916666,38.042000,29.303637,40.189258,NaN,NaN,0.803326,0.781927,-0.214444,-0.1412,127087.083618
24,2011-01-06,36.430000,36.730000,35.849998,36.320000,25.946287,3979600,-3212300,37.628333,37.843000,26.247120,37.439267,NaN,NaN,0.810994,0.786831,-0.218056,-0.1523,109570.484581
25,2011-01-07,36.400002,36.439999,35.750000,36.310001,25.939138,1152200,-4364500,37.275000,37.688000,26.141581,37.347679,0.264522,NaN,0.798894,0.781989,-0.160833,-0.1378,31732.304276
26,2011-01-10,35.189999,35.910000,35.150002,35.900002,25.646250,3388700,-7753200,36.868334,37.433000,21.823739,33.602568,0.132102,NaN,0.835005,0.800890,-0.161389,-0.1533,94392.752402
27,2011-01-11,36.730000,36.970001,36.529999,36.750000,26.253469,2000200,-5753000,36.550001,37.278000,44.591774,46.061773,0.094655,NaN,0.858504,0.814345,0.033333,-0.0528,54427.210884
28,2011-01-12,37.400002,37.549999,37.220001,37.480000,26.774967,1635800,-4117200,36.565001,37.221000,57.383171,54.253243,0.122471,NaN,0.852654,0.813628,0.152500,0.0259,43644.610459
29,2011-01-13,37.330002,37.660000,37.160000,37.290001,26.639235,973300,-5090500,36.675001,37.107000,53.523934,51.970747,0.127712,NaN,0.817388,0.797946,0.102500,0.0183,26100.830622
30,2011-01-14,38.669998,41.090000,38.639999,40.830002,29.168144,12561300,7470800,37.426668,37.356001,81.436765,74.328968,0.412756,NaN,1.115649,0.948049,0.567222,0.3474,307648.772586
31,2011-01-18,40.330002,40.599998,39.869999,40.099998,28.646646,3886900,3583900,38.058334,37.500000,70.899650,67.164998,0.573143,NaN,1.100085,0.948647,0.340277,0.2600,96930.179398
32,2011-01-19,39.349998,39.439999,36.950001,37.189999,26.567795,11033700,-7449800,38.273333,37.480000,43.793813,47.070746,0.460134,NaN,1.305076,1.058714,-0.180556,-0.0290,296684.600610
33,2011-01-20,36.889999,38.680000,36.759998,38.570000,27.553640,7719700,269900,38.576667,37.674000,53.837171,54.278405,0.476437,0.118528,1.366569,1.101779,-0.001111,0.0896,200147.783251
34,2011-01-21,39.040001,39.360001,38.820000,38.950001,27.825106,2598400,2868300,38.821667,37.937000,56.410881,56.107158,0.514093,0.124948,1.308912,1.086190,0.021389,0.1013,66711.166452

In [8]:
df.to_csv("data/ASML_v1.csv")

In [14]:
df['daily_diff'] = df['Close'].shift(-1) - df['Close']

In [17]:
df['daily_trend'] = np.sign(df['daily_diff'])

In [18]:
df['daily_trend']

0       1.0
1       1.0
2       1.0
3      -1.0
4      -1.0
       ...
1253    1.0
1254    1.0
1255    1.0
1256    1.0
1257    NaN
Name: daily_trend, Length: 1258, dtype: float64

In [19]:
df.to_csv("data/ASML_v1_with_trend.csv")